### ISSUE TITLE
Integrate new hacker terminal model

### ISSUE THREAD

**Issue by Bone008** [Bone008/HackerJedi#28] opened 2017-04-28 10:56 UTC
Challenge:
 * get the animation to work
 * place the trigger correctly

**Comment by PeterGreth** [comment] 2017-04-28 23:55
Now needed: Progress bar "Hacking in progress... |==== &nbsp;&nbsp;&nbsp; |"

**Comment by PeterGreth** [comment] 2017-05-02 01:58
Duplicate of #27

**Closed as completed by PeterGreth** 2017-05-02 01:58 UTC
Labels: prio: 3 - nicetohave, comp: General, type: GUI
